BEGIN TRANSACTION;

INSERT INTO `STATIONS` (id,name) VALUES (8012,'DE BROUCKERE');
INSERT INTO `STATIONS` (id,name) VALUES (8022,'GARE CENTRALE');
INSERT INTO `STATIONS` (id,name) VALUES (8272,'SAINTE-CATHERINE');
INSERT INTO `STATIONS` (id,name) VALUES (8282,'COMTE DE FLANDRE');
INSERT INTO `STATIONS` (id,name) VALUES (8292,'ETANGS NOIRS');
INSERT INTO `STATIONS` (id,name) VALUES (8382,'GARE DE L''OUEST');
INSERT INTO `STATIONS` (id,name) VALUES (8742,'BEEKKANT');


INSERT INTO `LINES` (id) VALUES (1);
INSERT INTO `LINES` (id) VALUES (2);
INSERT INTO `LINES` (id) VALUES (5);
INSERT INTO `LINES` (id) VALUES (6);

INSERT INTO `STOPS` (id_line,id_station,id_order) VALUES (1,8382,1);
INSERT INTO `STOPS` (id_line,id_station,id_order) VALUES (1,8742,2);
INSERT INTO `STOPS` (id_line,id_station,id_order) VALUES (1,8292,3);
INSERT INTO `STOPS` (id_line,id_station,id_order) VALUES (1,8282,4);
INSERT INTO `STOPS` (id_line,id_station,id_order) VALUES (1,8272,5);
INSERT INTO `STOPS` (id_line,id_station,id_order) VALUES (1,8012,6);
INSERT INTO `STOPS` (id_line,id_station,id_order) VALUES (1,8022,7);


COMMIT;